Revert "target specific patches have nothing to do in generic.."
This reverts commit r34230, as it is causing build failures:

 make[3] -C package/mtd compile
imagetag.c:35:32: fatal error: linux/bcm963xx_tag.h: No such file or directory
compilation terminated.
make[4]: *** [imagetag.o] Error 1

Any patches modifying exported kernel headers need to reside in generic
as toolchain/kernel-headers only applies generic patches.